openapi: 3.0.0
info:
  title: To-Do List API
  version: 1.0.0
  description: REST API для управления задачами на чистом PHP с JWT-аутентификацией.

servers:
  - url: http://localhost

paths:
  /register:
    post:
      summary: Регистрация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '201':
          description: Пользователь зарегистрирован
        '400':
          description: Ошибка валидации
        '409':
          description: Email уже используется

  /login:
    post:
      summary: Вход пользователя и получение JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthRequest'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Неверные учетные данные

  /tasks:
    get:
      summary: Получить список задач
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: status
          schema:
            type: string
        - in: query
          name: deadline
          schema:
            type: string
            format: date
        - in: query
          name: sort
          schema:
            type: string
        - in: query
          name: order
          schema:
            type: string
            enum: [asc, desc]
      responses:
        '200':
          description: Список задач
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Создать новую задачу
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Задача создана
        '400':
          description: Ошибка валидации

  /tasks/{id}:
    get:
      summary: Получить задачу по ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задача не найдена

    put:
      summary: Обновить задачу
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '200':
          description: Задача обновлена
        '400':
          description: Ошибка валидации
        '404':
          description: Задача не найдена

    delete:
      summary: Удалить задачу
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Задача удалена
        '404':
          description: Задача не найдена

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuthRequest:
      type: object
      properties:
        email:
          type: string
          example: test@example.com
        password:
          type: string
          example: secret123

    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [в работе, завершено, дедлайн]
        deadline:
          type: string
          format: date
        created_at:
          type: string
          format: date-time

    TaskCreate:
      type: object
      required: [title]
      properties:
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [в работе, завершено, дедлайн]
        deadline:
          type: string
          format: date
git add .